### ISSUE TITLE
What works

### ISSUE THREAD

**Issue by DrMadWill** [Zaladdin/CSharp#3]
[Burada](https://github.com/Zaladdin/CSharp/blob/493530809c7bbab3276555904dd0fb715c77476f/Programs/EdedOlan/Program.cs#L16) nə etməyə çalışmısan yada belə desək bu programin məqsədi nədir?

**Comment by Zaladdin** [comment]
Arrayin ədədlərin arasında hansının tərkibində 3 var onu çıxardır ekrana

**Comment by Zaladdin** [comment]
Daxilində 3 rəqəmi olan neçə ədəd olduğunu ekrana çap edən metod yazın


Mentor tasks, task 1, axırdan 3cu task)

**Comment by DrMadWill** [comment]
Anladim amma bu `readme.md` -ləri istifadə etməyəcəksənsə sil
